### ISSUE TITLE
Example notation

### ISSUE THREAD

**Issue by kyrgeorgiou** [LRydin/jumpdiff#4]
Hi @LRydin, thank you for this great package. I have a question regarding the notation in the definition of the jump term. The parameter xi is referred to as the jump amplitude, which is however normally distributed with variance sigma_xi. Is the xi parameter as set in the example actually the standard deviation of the jump amplitude? 

Furthermore, is there a way to set the initial condition, e.g., X_0 = 0?

Thanks again! 
Kyriakos

**Comment by LRydin** [comment]
Hey @kyrgeorgiou! Sorry for the delay, I totally missed the notification!

So, the `xi`, the jump amplitude, should be the *variance* of the normally distributed jumps. You can see in the code in [L.109](https://github.com/LRydin/jumpdiff/blob/144d38f4ea00291008bf940064d91371007bcc57/jumpdiff/jd_process.py#L109) that is enters `np.random.random()` as `scale=np.sqrt(xi)`, and `scale` expected a standard deviation.

To insert an initial condition to `jd_process()`, just use `init=X_0`, with your desired `X_0`. 

Hope this helps!

**Comment by kyrgeorgiou** [comment]
Hi @LRydin, 
Great, thanks so much for replying! This indeed helped :)
