### ISSUE TITLE
Reproducing the results in the exampels fails

### ISSUE THREAD

**Issue by sebglom** [LRydin/JumpDiff#7]
Thank you for this great work!

As a mechanical engineer, I currently do not have a strong mathematical background regarding the formulation of stochastic processes, but I would like to use this package to perform a Monte Carlo simulation for energy system analysis, e.g., by sampling projections of the development of energy prices. I tried to reproduce the results from the code snippets given by the examples in the documentation and was not able to achieve the same results. I have done the following:

Firstly, I have simulated a jump diffusion process using the same code given by your documentation:

```
# integration time and time sampling
t_final = 10000
delta_t = 0.001

# A drift function
def a(x):
    return -0.5*x

# and a (constant) diffusion term
def b(x):
    return 0.75

# Now define a jump amplitude and rate
xi = 2.5
lamb = 1.75

# and simply call the integration function
X = jd.jd_process(t_final, delta_t, a=a, b=b, xi=xi, lamb=lamb)
``` 

The plot of X is given below, and so far, it looks similar to the results given in the examples.
<img src="https://github.com/LRydin/jumpdiff/assets/121283864/fd28e62e-269f-4d03-ab58-c5d46df0f0b5" width="500">

Then I tried the ability of the package to estimate the given parameters, and the results started to become a bit confusing. I used the following code according to the documentation:

```
edges, moments = jd.moments(timeseries = X)

# we want the first power, so we need 'moments[1,...]'
plt.plot(edges, moments[1,...], label='D1')
plt.plot(edges, moments[2,...], label='D2')

plt.xlabel('x') 
plt.ylabel('D_m(x)')  
plt.legend()

plt.xlim(-5, 5) 

plt.show()
```

<img src="https://github.com/LRydin/jumpdiff/assets/121283864/55f529a5-a898-4301-9d57-2bbced16e992" width="500">

The results show the first two Kramers-Moyal coefficients. In comparison with the results in the documentation for the same simulation, the values of the coefficients seem to be completely different:

![grafik](https://github.com/LRydin/jumpdiff/assets/121283864/419a50de-8251-4e86-9e36-26c7ed0c2350)

![grafik](https://github.com/LRydin/jumpdiff/assets/121283864/df8d43cb-4256-4093-b230-eb7c62b9c35a)

I have also looked into your paper. Figure 2 shows the estimation results for the coefficients based on the same simulation. Here, the second Kramers-Moyal coefficient D2 shows again a different value (shown below). In this case, it seems to directly correspond to the constant value b that was chosen in the model parametrization, whereas the former results are stating that the resulting curve is also dependent on the parameters of the jump process.

![grafik](https://github.com/LRydin/jumpdiff/assets/121283864/b9cc4e29-acb0-471d-aea9-3799b983d99b)

Could you clarify my observations a bit and provide some more guidance on how I can retrieve the final parameters of the jump diffusion process based on the Kramers-Moyal coefficients? There might be a huge misunderstanding on my side since I am currently not very familiar with the deep theory behind the package.

Thank you so far!

**Comment by LRydin** [comment]
Hey @sebglom you are absolutely right, I forgot to include that you have to divide the `moments` by `delta_t`. Can you try that quickly with your script, i.e., simply change:

```python
plt.plot(edges, moments[1,...], label='D1')
plt.plot(edges, moments[2,...], label='D2')
```
to 
```python
plt.plot(edges, moments[1,...]/delta_t, label='D1')
plt.plot(edges, moments[2,...]/delta_t, label='D2')
```

The results should look much more like the figures, with D1 being linear with a negative slope and D2 being approximately constant around the value 0.75² + 2.5×1.75 = 4.9375 (maybe divided by 2? there might be a factor of 2 here somewhere)

Does that give more sensible results?

**Comment by sebglom** [comment]
Hi @LRydin,

thank you very much for this fast response! In the moment as i submitted this issue i had the same idea :-) Now everything does make more sense. Maybe you could update the documentation including the code for the final estimation of the parameters.

Would it make more sense to include the scaling in the source code within the functions so that the user already get the values according to the equation 7 in the paper?

![grafik](https://github.com/LRydin/jumpdiff/assets/121283864/b67c0101-7168-4046-a9d5-83eda8689e29)

**Comment by LRydin** [comment]
@sebglom I should indeed!
I thought about that at the time, but there is one drawback: Sometimes you don't necessarily have access to the time sampling of the data. In another matter, when you do, you might know the sampling rate (e.g. 15 minutes) but you might not know the units of the various other constants, thus it is not straightforward to divide by `delta_t` (e.g. should `delta_t` be 15 mins or 300 seconds?) - therefore I left is as is: independent of `delta_t`.


To-dos:

- [ ] Update Documentation to include `delta_t` division

**Comment by sebglom** [comment]
@LRydin okay this does make sense! Thank you very much.
