### ISSUE TITLE
Estimating a(x, t) and b(x, t) in the Equation dX(t) = a(x, t) dt + b(x, t) dW(t) + ξdJ(t)

### ISSUE THREAD

**Issue by jaeminSon** [LRydin/JumpDiff#8]
Thanks for sharing nice codes. By the way, I failed to find any method that finds a(x,t) and b(x,t) right away even in your paper (https://www.jstatsoft.org/article/view/v105i04/4421).

Can you provide any hints to do that?

**Comment by LRydin** [comment]
Hey @jaeminSon, nice to know you are interested in the `jumpdiff` package. Have you looked at the [readme](https://github.com/LRydin/jumpdiff) of the github page? [Here](https://github.com/LRydin/jumpdiff#:~:text=Using%20jumpdiff%20to%20retrieve%20the%20parameters) you find a way to estimate `a(x,t)` and `b(x,t)`

```python

import jumpdiff as jd
import matplotlib.plotly as plt

# consider a one-dimensional time series X

edges, moments = jd.moments(timeseries = X)

plt.plot(edges, moments[1,...])  # this is your a(x) function (no time dependence)
plt.plot(edges, moments[2,...])  # this is your b(x) function (no time dependence)
```

Is this what you are looking for?

**Comment by jaeminSon** [comment]
Thanks a lot for your kind explanation! Is **moments[2,...]** equal to b(x)? or Shall I subtract xi and lambda computed with **jump_amplitude** and **jump_rate** methods and take square root on it?

**Comment by LRydin** [comment]
Correction: If you indeed have a jump-diffusion process, to estimate the diffusion coefficient `b(x)`, you need to also estimate the jump parameters. Note that the conditional moments `moments`, more precisely, `moments[2,...]` is given by

```python
moments[2,...] = b^2 + λξ
```
thus you will need to subtract the jump parameter, which you obtain with
```python
# first estimate the jump amplitude
xi_est = jd.jump_amplitude(moments = moments)

# and now estimated the jump rate
lamb_est = jd.jump_rate(moments = moments)
```
